services:
    c2is_doctrine_cache_invalidator.cache_invalidator:
        class: C2is\DoctrineCacheInvalidationBundle\EventListener\CacheInvalidator
        arguments:
            - '@c2is_doctrine_cache_invalidator.configuration_loader'
            - '@c2is_doctrine_cache_invalidator.cache_invalidator_driver'
            - '@c2is_doctrine_cache_invalidator.cache_provider_driver'
            - '%c2is_doctrine_cache_invalidator.doctrine_cache_driver_options%'
        tags:
            - { name: doctrine.event_listener, event: onFlush }

    c2is_doctrine_cache_invalidator.configuration_loader.annotation:
        class: C2is\DoctrineCacheInvalidationBundle\Loader\AnnotationCacheConfigurationLoader
        arguments:
            - '@annotations.reader'

    c2is_doctrine_cache_invalidator.configuration_loader.yml:
        class: C2is\DoctrineCacheInvalidationBundle\Loader\YmlCacheConfigurationLoader
        arguments:
            - '%kernel.root_dir%'
            - '%c2is_doctrine_cache_invalidator.yml_file%'

    c2is_doctrine_cache_invalidator.cache_invalidator_driver.abstract:
        class: C2is\DoctrineCacheInvalidationBundle\CacheInvalidatorDriver\AbstractCacheInvalidatorDriver
        abstract: true
        calls:
            - ['setDebug', ['%kernel.debug%']]
            - ['setEventDispatcher', ['@event_dispatcher']]
            - ['setPropertyAccessor', ['@property_accessor']]

    c2is_doctrine_cache_invalidator.cache_invalidator_driver.default:
        class: C2is\DoctrineCacheInvalidationBundle\CacheInvalidatorDriver\CacheInvalidatorDefaultDriver
        parent: c2is_doctrine_cache_invalidator.cache_invalidator_driver.abstract

    c2is_doctrine_cache_invalidator.cache_invalidator_driver.gedmo:
        class: C2is\DoctrineCacheInvalidationBundle\CacheInvalidatorDriver\CacheInvalidatorGedmoDriver
        parent: c2is_doctrine_cache_invalidator.cache_invalidator_driver.abstract

    c2is_doctrine_cache_invalidator.cache_provider_driver.array:
        class: C2is\DoctrineCacheInvalidationBundle\CacheProviderDriver\ArrayProvider

    c2is_doctrine_cache_invalidator.cache_provider_driver.predis:
        class: C2is\DoctrineCacheInvalidationBundle\CacheProviderDriver\PredisProvider
